version: 1.2
workflows:
  - name: "MultiScaleFootprintingWorkflow"
    subclass: WDL
    primaryDescriptorPath: /print.wdl
    authors: "Zhijian Li"
    topic: Performing multi-scale footprinting
    filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
         tags:
             - /.*/